In [1]:
import os
import pandas
os.listdir()

['.ipynb_checkpoints',
 'Filtering.ipynb',
 'Loading.ipynb',
 'Setting.ipynb',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [2]:
df1 = pandas.read_csv('supermarkets-commas.txt')
df2 = pandas.read_csv('supermarkets-semi-colons.txt')
df3 = pandas.read_csv('supermarkets.csv')
df4 = pandas.read_json('supermarkets.json')
df5 = pandas.read_excel('supermarkets.xlsx')

In [ ]:
df7exp = df3.set_index("Address")
df7exp

,ID,City,State,Country,Name,Employees
Address,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,3,San Francisco,California 94114,USA,Super River,25
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20

In [10]:
#archive.loc[Fila,Columna]#]
#df7exp.loc["FilaRango1":"FilaRango2","ColumnaRango1": "ColumnaRango2"]#
df7exp.loc["735 Dolores St":"332 Hill St","ID": "State"] #Busqueda por Rangos#

                ID           City             State
Address
735 Dolores St   2  San Francisco          CA 94119
332 Hill St      3  San Francisco  California 94114

In [12]:
#Interseccion entre Fila y Columna
df7exp.loc["332 Hill St", "State"]

'California 94114'

In [25]:
#Listo los elemento de una Columna
list(df7.loc[:,"Name"])

['Madeira',
 'Bready Shop',
 'Super River',
 "Ben's Shop",
 'Sanchez',
 'Richvalley']

In [21]:
#Listar los elemtos de un Indice
list(df7.loc["332 Hill St",])

[np.int64(3),
 'San Francisco',
 'California 94114',
 'USA',
 'Super River',
 np.int64(25)]

In [26]:
df7

,ID,City,State,Country,Name,Employees
Address,,,,,,
3666 21st St,1,San Francisco,CA 94114,USA,Madeira,8
735 Dolores St,2,San Francisco,CA 94119,USA,Bready Shop,15
332 Hill St,3,San Francisco,California 94114,USA,Super River,25
3995 23rd St,4,San Francisco,CA 94114,USA,Ben's Shop,10
1056 Sanchez St,5,San Francisco,California,USA,Sanchez,12
551 Alvarado St,6,San Francisco,CA 94114,USA,Richvalley,20

In [32]:
#Buscar por posiciones los elementos de una tabla#
df1.iloc[0:4, 1:4]

          Address           City             State
0    3666 21st St  San Francisco          CA 94114
1  735 Dolores St  San Francisco          CA 94119
2     332 Hill St  San Francisco  California 94114
3    3995 23rd St  San Francisco          CA 94114